FROM public.ecr.aws/v0a2l7y2/wilco/anythink-frontend-react:latest

RUN curl https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh --output /wait-for-it.sh
RUN chmod +x /wait-for-it.sh